# -*- coding: utf-8 -*-
"""Sorority Matching Sample Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13RijvwRfid7KsApY6OXYgOOCAv1zDubN
"""

#Imports/Reading in all data
import pandas as pd
import numpy as np
import re
import networkx as nx

bump_team_id = "17k1SjqTAxTp_fMtgkOg31aQG7fkKv8ehoGf4d_Q9Rcs"
bump_team_url = f"https://docs.google.com/spreadsheets/d/{bump_team_id}/gviz/tq?tqx=out:csv&gid=0"
bump_teams = pd.read_csv(bump_team_url)

party_excuses_id = "1JYgg0v8UYfbQntMfcrh9fHlU8EWhiExhOYYakOMD3VU"
party_excuses_url = f"https://docs.google.com/spreadsheets/d/{party_excuses_id}/gviz/tq?tqx=out:csv&gid=0"
party_excuses = pd.read_csv(party_excuses_url)

pnm_intial_interest = pd.read_csv("synthetic_pnm_responses.csv")

member_interest_id = "1dcOXl5MEHGhjEORfN1jHzsu7uUwbYMS0VyUVCT24ahk"
member_interest_url = f"https://docs.google.com/spreadsheets/d/{member_interest_id}/gviz/tq?tqx=out:csv&gid=0"
member_interest = pd.read_csv(member_interest_url)

member_pnm_no_match_id = "1X-dQ5j5zWYf5tGvceDpncQdFUjrVGeR-9Q3kFR_GyJU"
member_pnm_no_match_url = f"https://docs.google.com/spreadsheets/d/{member_pnm_no_match_id}/gviz/tq?tqx=out:csv&gid=0"
member_pnm_no_match = pd.read_csv(member_pnm_no_match_url)

#MANUALLY CREATING PNM PARTY ASSIGNMENTS, ASSUMING 37 PARTIES
# 1. Slice the dataframe to get exactly 1665 PNMs
pnm_intial_interest = pnm_intial_interest.iloc[0:1665].copy()

# 2. Setup the variables
num_parties = 37
pnms_per_party = 45 # 1665 / 37 = 45

# 3. Create the assignments
# np.tile repeats the array [1, 2, ..., 37] exactly 45 times
party_assignments = np.tile(np.arange(1, num_parties + 1), pnms_per_party)

# 4. Shuffle the assignments so they are random
np.random.seed(42)
np.random.shuffle(party_assignments)

# 5. Add the new column
pnm_intial_interest['Party'] = party_assignments

print(pnm_intial_interest.head())

import pandas as pd
import numpy as np
import difflib
from sentence_transformers import SentenceTransformer
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics.pairwise import haversine_distances
from math import radians

# --- STEP 1: PREPARE WORKING DATA ---
# Create working copies
df_mem = member_interest.copy()
df_pnm = pnm_intial_interest.copy()

# Standardize PNM column names
pnm_col_map = {
    'Enter your name:': 'Full Name',
    'Enter your hometown in the form City, State:': 'Hometown',
    'Enter your major or "Undecided":': 'Major',
    'Enter your minor or leave blank:': 'Minor',
    'Enter your high school involvement (sports, clubs etc.), separate each activity by a comma:': 'High School Involvement',
    'Enter your college involvement (sports, clubs etc.), separate each activity by a comma:': 'College Involvement',
    'Enter your hobbies and interests, separate each activity by a comma:': 'Hobbies',
    'Pick your year in school:': 'Year'
}
df_pnm.rename(columns=pnm_col_map, inplace=True)

import pandas as pd
import difflib

# --- STEP 2: GEOCODING (OFFLINE) ---
url = "https://raw.githubusercontent.com/kelvins/US-Cities-Database/main/csv/us_cities.csv"

try:
    ref_df = pd.read_csv(url)

    # Create the lookup key
    ref_df['MATCH_KEY'] = (ref_df['CITY'] + ", " + ref_df['STATE_CODE']).str.upper()

    # 1. Drop duplicates to ensure we only have unique City, State combinations
    # keep='first' retains the first entry found for that city
    ref_df = ref_df.drop_duplicates(subset=['MATCH_KEY'], keep='first')

    # 2. Use zip for fast dictionary creation
    # This avoids the overhead of DataFrame indexing and transposition
    city_coords_map = {
        key: [lat, lon]
        for key, lat, lon in zip(ref_df['MATCH_KEY'], ref_df['LATITUDE'], ref_df['LONGITUDE'])
    }

    ALL_CITY_KEYS = list(city_coords_map.keys())

except Exception as e:
    city_coords_map = {}
    ALL_CITY_KEYS = []

def get_coords_offline(hometown_str):
    if not isinstance(hometown_str, str): return None, None
    key = hometown_str.strip().upper()

    # Exact Match
    if key in city_coords_map:
        return city_coords_map[key][0], city_coords_map[key][1]

    # Fuzzy Match
    matches = difflib.get_close_matches(key, ALL_CITY_KEYS, n=1, cutoff=0.8)
    if matches:
        return city_coords_map[matches[0]][0], city_coords_map[matches[0]][1]

    return None, None

# --- STEP 3: COMBINED GEO CLUSTERING ---
# We cluster everyone together so "Arlington, VA" (Member) and "Alexandria, VA" (PNM)
# end up in the same "Arlington" group.

all_coords = []
# We track origin to split them back apart later
# Structure: (lat, lon, type, id, original_hometown_str)
geo_tracker = []

# Process Members
for idx, row in df_mem.iterrows():
    lat, lon = get_coords_offline(row['Hometown'])
    if lat is not None:
        r_lat, r_lon = radians(lat), radians(lon)
        all_coords.append([r_lat, r_lon])
        geo_tracker.append({'type': 'mem', 'id': row['Sorority ID'], 'hometown': row['Hometown']})

# Process PNMs
for idx, row in df_pnm.iterrows():
    lat, lon = get_coords_offline(row['Hometown'])
    if lat is not None:
        r_lat, r_lon = radians(lat), radians(lon)
        all_coords.append([r_lat, r_lon])
        geo_tracker.append({'type': 'pnm', 'id': row['PNM ID'], 'hometown': row['Hometown']})

# Cluster
mem_geo_tags = {}
pnm_geo_tags = {}

if all_coords:
    dist_matrix = haversine_distances(all_coords, all_coords) * 3958.8
    geo_clustering = AgglomerativeClustering(
        n_clusters=None, distance_threshold=30, metric='precomputed', linkage='single'
    )
    geo_labels = geo_clustering.fit_predict(dist_matrix)

    # Determine Group Names
    geo_groups = {}
    for i, label in enumerate(geo_labels):
        if label not in geo_groups: geo_groups[label] = []
        geo_groups[label].append(geo_tracker[i]['hometown'])

    # Assign Tags
    for i, label in enumerate(geo_labels):
        group_name = geo_groups[label][0] # Pick first hometown as the "Region Name"
        tracker = geo_tracker[i]

        if tracker['type'] == 'mem':
            mem_geo_tags[tracker['id']] = group_name
        else:
            pnm_geo_tags[tracker['id']] = group_name

# --- STEP 4: COMBINED SEMANTIC CLUSTERING ---
# We cluster interests together so "Volleyball" (Member) and "Club V-Ball" (PNM) match.

model = SentenceTransformer('all-MiniLM-L6-v2')
all_terms_list = []

# Helper to collect terms
def extract_terms(row, cols):
    text_parts = [str(row.get(c, '')).lower() for c in cols]
    combined = ", ".join([p for p in text_parts if p != 'nan' and p.strip() != ''])
    return [t.strip() for t in combined.split(',') if t.strip()]

# Collect Member Terms
mem_interest_map = [] # (id, term)
for idx, row in df_mem.iterrows():
    terms = extract_terms(row, ['Major', 'Minor', 'Hobbies', 'College Involvement', 'High School Involvement'])
    for term in terms:
        all_terms_list.append(term)
        mem_interest_map.append({'id': row['Sorority ID'], 'term': term})

# Collect PNM Terms
pnm_interest_map = [] # (id, term)
for idx, row in df_pnm.iterrows():
    terms = extract_terms(row, ['Major', 'Minor', 'Hobbies', 'College Involvement', 'High School Involvement'])
    for term in terms:
        all_terms_list.append(term)
        pnm_interest_map.append({'id': row['PNM ID'], 'term': term})

# Cluster
term_to_group = {}
if all_terms_list:
    unique_terms = list(set(all_terms_list))
    embeddings = model.encode(unique_terms)
    sem_clustering = AgglomerativeClustering(
        n_clusters=None, distance_threshold=0.5, metric='cosine', linkage='average'
    )
    sem_labels = sem_clustering.fit_predict(embeddings)

    # Name the clusters (Shortest word wins)
    temp_map = {}
    for term, label in zip(unique_terms, sem_labels):
        if label not in temp_map: temp_map[label] = []
        temp_map[label].append(term)

    for label, terms in temp_map.items():
        # Pick the shortest term as the "Attribute Name"
        attr_name = min(terms, key=len)
        for term in terms:
            term_to_group[term] = attr_name

# --- STEP 5: AGGREGATE AND SAVE ---

# Helper to fuzzy match years (Independent per person)
VALID_YEARS = ["Freshman", "Sophomore", "Junior", "Senior"]
def get_year_tag(year_val):
    if pd.isna(year_val): return None
    raw = str(year_val).strip()
    matches = difflib.get_close_matches(raw, VALID_YEARS, n=1, cutoff=0.6)
    return matches[0] if matches else raw.title()

# --- A. Finalize Members ---
mem_final_attrs = {row['Sorority ID']: set() for _, row in df_mem.iterrows()}

for idx, row in df_mem.iterrows():
    pid = row['Sorority ID']
    # Year
    yt = get_year_tag(row['Year'])
    if yt: mem_final_attrs[pid].add(yt)
    # Geo
    if pid in mem_geo_tags: mem_final_attrs[pid].add(mem_geo_tags[pid])

for entry in mem_interest_map:
    pid = entry['id']
    if entry['term'] in term_to_group:
        mem_final_attrs[pid].add(term_to_group[entry['term']])

member_interest['attributes_for_matching'] = df_mem['Sorority ID'].map(
    lambda x: ", ".join(mem_final_attrs.get(x, set()))
)

# --- B. Finalize PNMs ---
pnm_final_attrs = {row['PNM ID']: set() for _, row in df_pnm.iterrows()}

for idx, row in df_pnm.iterrows():
    pid = row['PNM ID']
    # Year
    yt = get_year_tag(row['Year'])
    if yt: pnm_final_attrs[pid].add(yt)
    # Geo
    if pid in pnm_geo_tags: pnm_final_attrs[pid].add(pnm_geo_tags[pid])

for entry in pnm_interest_map:
    pid = entry['id']
    if entry['term'] in term_to_group:
        pnm_final_attrs[pid].add(term_to_group[entry['term']])

pnm_intial_interest['attributes_for_matching'] = df_pnm['PNM ID'].map(
    lambda x: ", ".join(pnm_final_attrs.get(x, set()))
)

!pip install xlsxwriter

import pandas as pd
import networkx as nx
import re

# --- 0. Initial Data Cleaning (Columns) ---
try:
    bump_teams.columns = bump_teams.columns.str.strip()
    party_excuses.columns = party_excuses.columns.str.strip()
    pnm_intial_interest.columns = pnm_intial_interest.columns.str.strip()
    member_interest.columns = member_interest.columns.str.strip()
    member_pnm_no_match.columns = member_pnm_no_match.columns.str.strip()
except NameError:
    print("Dataframes not loaded. Please ensure CSVs are read before running this block.")

# --- Helper Function for Auto-Adjusting Excel Columns ---
def auto_adjust_columns(writer, sheet_name, df):
    """
    Adjusts the column width of the specified worksheet to fit the content.
    """
    worksheet = writer.sheets[sheet_name]
    for idx, col in enumerate(df.columns):
        # Calculate max length of data in column (including header)
        max_len = max(
            df[col].astype(str).map(len).max(),
            len(str(col))
        ) + 2  # Add a little padding
        worksheet.set_column(idx, idx, max_len)

# --- 1. User Inputs ---
while True:
    try:
        user_input = input("Enter the total number of parties: ")
        num_of_parties = int(user_input)
        if num_of_parties > 0:
            break
        else:
            print("Please enter a number greater than 0.")
    except ValueError:
        print("Invalid input. Please enter a valid integer.")

while True:
    try:
        user_input = input("Enter the number of PNM matches needed for each bump team (Capacity): ")
        num_pnm_matches_needed = int(user_input)
        if num_pnm_matches_needed > 0:
            break
        else:
            print("Please enter a number greater than 0.")
    except ValueError:
        print("Invalid input. Please enter a valid integer.")

# --- NEW INPUT: Number of Rounds ---
while True:
    try:
        user_input = input("Enter the number of Rounds per Party: ")
        num_rounds_party = int(user_input)
        if num_rounds_party > 0:
            break
        else:
            print("Please enter a number greater than 0.")
    except ValueError:
        print("Invalid input. Please enter a valid integer.")

while True:
    bump_order_set = input("Is the bump order set? (y/n): ").strip().lower()
    if bump_order_set in ['y', 'n']:
        break
    else:
        print("Invalid input. Please enter 'y' for yes or 'n' for no.")

print("\n")

# --- 2. Data Cleaning & Setup ---
member_interest["Full Name"] = member_interest["First Name"] + " " + member_interest["Last Name"]
pnm_intial_interest["Enter your name:"] = pnm_intial_interest["First Name"] + " " + pnm_intial_interest["Last Name"]

# Clean and Explode Party Excuses
party_excuses["Choose the party/parties you are unable to attend:"] = party_excuses["Choose the party/parties you are unable to attend:"].apply(
    lambda x: [int(i) for i in re.findall(r'\d+', str(x))] if pd.notnull(x) else []
)
party_excuses = party_excuses.explode("Choose the party/parties you are unable to attend:")

# Clean and Explode No-Match lists
member_pnm_no_match["Choose the PNM or PNMs you should NOT match with:"] = member_pnm_no_match["Choose the PNM or PNMs you should NOT match with:"].str.split(r',\s*', regex=True)
member_pnm_no_match = member_pnm_no_match.explode("Choose the PNM or PNMs you should NOT match with:")

# Build Caches
member_attr_cache = {
    row['Sorority ID']: set(str(row.get('attributes_for_matching', '')).split(', '))
    if row.get('attributes_for_matching') else set()
    for row in member_interest.to_dict('records')
}
name_to_id_map = member_interest.set_index('Full Name')['Sorority ID'].to_dict()

all_member_traits = member_interest['attributes_for_matching'].str.split(', ').explode()
trait_freq = all_member_traits.value_counts()
trait_weights = (len(member_interest) / trait_freq).to_dict()

strength_bonus_map = {1: 1.5, 2: 1.0, 3: 0.5, 4: 0.0}

no_match_pairs = {
    (row["Choose your name:"], row["Choose the PNM or PNMs you should NOT match with:"])
    for row in member_pnm_no_match.to_dict('records')
}

# --- 3. Main Processing Loop ---
for party in range(1, num_of_parties + 1):
    pnms_df = pnm_intial_interest[pnm_intial_interest['Party'] == party].copy()
    pnm_list = []
    pnm_records = pnms_df.to_dict('records')

    # Build PNM List
    for i, row in enumerate(pnm_records):
        p_attrs = set(str(row['attributes_for_matching']).split(', '))
        p_rank = row.get("Average Recruit Rank", 1.0)
        pnm_list.append({
            'idx': i,
            'id': row['PNM ID'],
            'name': row['Enter your name:'],
            'attrs': p_attrs,
            'rank': p_rank,
            'bonus': 0.75 * (p_rank - 1),
            'node_id': f"p_{i}"
        })

    # Get set of excused members for this party
    party_excused_names = set(party_excuses[party_excuses["Choose the party/parties you are unable to attend:"] == party]["Choose your name:"])

    # -------------------------------------------------------------
    # Team Parsing
    # -------------------------------------------------------------
    team_list = []
    broken_teams_list = []

    for raw_idx, row in enumerate(bump_teams.to_dict('records')):
        submitter = row["Choose your name:"]
        partners_str = str(row.get("Choose the name(s) of your bump partner(s):", ""))

        if partners_str.lower() == 'nan':
            partners = []
        else:
            partners = [p.strip() for p in re.split(r'[,;]\s*', partners_str) if p.strip()]

        current_members = [submitter] + partners
        missing_members = [m for m in current_members if m in party_excused_names]

        if missing_members:
            broken_teams_list.append({'members': current_members, 'missing': missing_members})
        else:
            t_rank = row.get("Bump Team Ranking:", 4)
            team_list.append({
                't_idx': len(team_list),
                'members': current_members,
                'team_size': len(current_members),
                'member_ids': [name_to_id_map.get(m) for m in current_members],
                'joined_names': ", ".join(current_members),
                'bonus': strength_bonus_map.get(t_rank, 0.0),
                'node_id': f"t_{len(team_list)}",
                'row_data': row # Store original row data to access RGL info later
            })

    # -------------------------------------------------------------
    # LOGIC CHECK: Capacity & Broken Teams
    # -------------------------------------------------------------
    total_capacity = len(team_list) * num_pnm_matches_needed

    # ONLY RUN THIS CHECK IF CAPACITY IS LOW
    if total_capacity < len(pnm_list):
        print(f"Warning: Party {party} has {len(pnm_list)} PNMs but only capacity for {total_capacity} matches as there are {len(team_list)} bump teams who can each have {num_pnm_matches_needed} PNMs matched to them.")

        if not party_excused_names:
            print("No members are explicitly excused.")
            # Create quick lookup sets for who is actually in the room
            active_members_in_party = {m for t in team_list for m in t['members']}
            active_pnms_in_party = {p['name'] for p in pnm_list}
            active_conflicts = []

            # Iterate through the global no-match list and see if both are present
            for (m_name, p_name) in no_match_pairs:
              if m_name in active_members_in_party and p_name in active_pnms_in_party:
                active_conflicts.append(f"Member {m_name} and PNM {p_name}")

            if active_conflicts:
              print(f"Found {len(active_conflicts)} active 'No Match' pairs present in this party:")
              for conflict in active_conflicts:
                print(f"   - {conflict}")
            else:
              print("No active 'No Match' conflicts found among the people present.")
        else:
            print(f"The following Bump Teams were removed due to excuses:")
            for item in broken_teams_list:
                members_str = ", ".join(item['members'])
                missing_str = ", ".join(item['missing'])
                print(f"Team: {members_str} (Missing: {missing_str})")

    # -------------------------------------------------------------
    # Score Potential Pairs (PNM to TEAM)
    # -------------------------------------------------------------
    potential_pairs = []

    for p_data in pnm_list:
        for t_data in team_list:
            if any((m, p_data['name']) in no_match_pairs for m in t_data['members']):
                continue

            score = 0
            reasons_list = []
            for m_id, m_name in zip(t_data['member_ids'], t_data['members']):
                if m_id is None: continue
                m_attrs = member_attr_cache.get(m_id, set())
                shared = p_data['attrs'].intersection(m_attrs)
                if shared:
                    for trait in shared:
                        score += trait_weights.get(trait, 1.0)
                        reasons_list.append(f"{p_data['name']} has {trait} in common with {m_name}.")

            total_score = score + t_data['bonus'] + p_data['bonus']
            final_cost = 1 / (1 + total_score)
            reason_sentence = " ".join(reasons_list) if reasons_list else "No specific attribute matches found."

            potential_pairs.append({
                'p_id': p_data['id'],
                'p_name': p_data['name'],
                'p_attrs': p_data['attrs'],
                't_idx': t_data['t_idx'],
                'team_size': t_data['team_size'],
                'p_node': p_data['node_id'],
                't_node': t_data['node_id'],
                'cost': final_cost,
                'pnm_rank': p_data['rank'],
                'team_members': t_data['joined_names'],
                'reasons': reason_sentence
            })

    potential_pairs.sort(key=lambda x: (x['cost'], -x['pnm_rank']))
    matchable_pnm_ids = {p['p_id'] for p in potential_pairs}

    # =========================================================================
    # PHASE A: GLOBAL MATCHING (Assign PNM to Bump Team)
    # =========================================================================

    global_flow_results = []
    assignments_map_flow = {t['t_idx']: [] for t in team_list}

    G = nx.DiGraph()
    source, sink, no_match_node = 'source', 'sink', 'dummy_nomatch'
    total_flow = len(pnm_list)

    G.add_node(source, demand=-total_flow)
    G.add_node(sink, demand=total_flow)
    G.add_node(no_match_node)

    for p in pnm_list:
        G.add_edge(source, p['node_id'], capacity=1, weight=0)
        # High weight to ensure it's a last resort
        G.add_edge(p['node_id'], no_match_node, capacity=1, weight=1000000)

    for t in team_list:
        G.add_edge(t['node_id'], sink, capacity=num_pnm_matches_needed, weight=0)

    G.add_edge(no_match_node, sink, capacity=total_flow, weight=0)

    for pair in potential_pairs:
        G.add_edge(pair['p_node'], pair['t_node'], capacity=1, weight=int(pair['cost'] * 10000))

    try:
        flow_dict = nx.min_cost_flow(G)
        pair_lookup = {(p['p_node'], p['t_node']): p for p in potential_pairs}

        # Identify PNMs that have ZERO potential matches due to 'No Match' lists
        pnm_ids_with_potential = {p['p_id'] for p in potential_pairs}

        for p_data in pnm_list:
            p_node = p_data['node_id']
            if p_node in flow_dict:
                for t_node, flow in flow_dict[p_node].items():
                    if flow > 0:
                        if t_node == no_match_node:
                            # SPECIFIC REASON LOGIC
                            if p_data['id'] not in pnm_ids_with_potential:
                                reason = "No match: Conflict list (all present teams blocked)"
                            else:
                                reason = "No match: All compatible teams at capacity"

                            global_flow_results.append({
                                'PNM ID': p_data['id'], 'PNM Name': p_data['name'],
                                'Bump Team Members': "NO MATCH", 'Match Cost': None,
                                'Reason': reason
                            })
                        else:
                            match_info = pair_lookup.get((p_node, t_node))
                            if match_info:
                                global_flow_results.append({
                                    'PNM ID': p_data['id'], 'PNM Name': p_data['name'],
                                    'Bump Team Members': match_info['team_members'], 'Match Cost': round(match_info['cost'], 4),
                                    'Reason': match_info['reasons']
                                })
                                assignments_map_flow[match_info['t_idx']].append(match_info)
    except nx.NetworkXUnfeasible:
        print(f"Global Flow Unfeasible for Party {party}")

    # --- A2. Global Greedy ---
    global_greedy_results = []
    assignments_map_greedy = {t['t_idx']: [] for t in team_list}
    matched_pnm_ids = set()
    team_counts = {t['t_idx']: 0 for t in team_list}

    # First, process valid pairs
    for pair in potential_pairs:
        if pair['p_id'] not in matched_pnm_ids:
            if team_counts[pair['t_idx']] < num_pnm_matches_needed:
                matched_pnm_ids.add(pair['p_id'])
                team_counts[pair['t_idx']] += 1
                global_greedy_results.append({
                    'PNM ID': pair['p_id'], 'PNM Name': pair['p_name'],
                    'Bump Team Members': pair['team_members'], 'Match Cost': round(pair['cost'], 4),
                    'Reason': pair['reasons']
                })
                assignments_map_greedy[pair['t_idx']].append(pair)

    # Second, identify why the remaining PNMs failed
    for p_data in pnm_list:
        if p_data['id'] not in matched_pnm_ids:
            # Check if they were even in the potential_pairs (No Match check)
            was_blocked_by_no_match = not any(p['p_id'] == p_data['id'] for p in potential_pairs)

            if was_blocked_by_no_match:
                greedy_reason = "No match: Conflict list (blocked from all teams)"
            else:
                greedy_reason = "No match: Room capacity reached (Greedy)"

            global_greedy_results.append({
                'PNM ID': p_data['id'], 'PNM Name': p_data['name'],
                'Bump Team Members': "NO MATCH", 'Match Cost': None,
                'Reason': greedy_reason
            })

    # =========================================================================
    # PHASE B: INTERNAL ROTATIONS (WITH RGL LOGIC)
    # =========================================================================

    def run_internal_rotation(assignment_map, method='flow'):
        rotation_output = []

        # --- MODIFIED: RESTRICT ROUNDS IF BUMP ORDER IS SET ---
        actual_rounds = 1 if bump_order_set == 'y' else num_rounds_party

        for t_idx, assigned_pnms in assignment_map.items():
            if not assigned_pnms: continue

            team_data = next((t for t in team_list if t['t_idx'] == t_idx), None)
            if not team_data: continue

            raw_rgl = team_data['row_data'].get('Choose your Bump Group Leader (RGL). Leave blank if none.', '')
            team_rgl_name = "" if pd.isna(raw_rgl) or str(raw_rgl).lower() == 'nan' else str(raw_rgl).strip()

            valid_members = []
            for m_id, m_name in zip(team_data['member_ids'], team_data['members']):
                if m_id: valid_members.append({'id': m_id, 'name': m_name})

            history = set()

            for round_num in range(1, actual_rounds + 1):
                if round_num == 1 and team_rgl_name:
                    active_members = [m for m in valid_members if m['name'].strip() != team_rgl_name]
                else:
                    active_members = valid_members

                must_allow_repeats = round_num > len(active_members)

                if method == 'flow':
                    sub_G = nx.DiGraph()
                    sub_s, sub_t = 's', 't'
                    req = len(assigned_pnms)
                    sub_G.add_node(sub_s, demand=-req)
                    sub_G.add_node(sub_t, demand=req)

                    for p in assigned_pnms:
                        sub_G.add_edge(sub_s, f"p_{p['p_id']}", capacity=1, weight=0)
                    for m in active_members:
                        sub_G.add_edge(f"m_{m['id']}", sub_t, capacity=1, weight=0)

                    for p in assigned_pnms:
                        for m in active_members:
                            is_repeat = (p['p_id'], m['id']) in history
                            if is_repeat and not must_allow_repeats: continue
                            m_attrs = member_attr_cache.get(m['id'], set())
                            shared = p['p_attrs'].intersection(m_attrs)
                            score = sum(trait_weights.get(t, 1.0) for t in shared)
                            base_cost = int((1/(1+score))*10000)
                            final_cost = base_cost + 50000 if is_repeat else base_cost
                            reason = ", ".join(shared) if shared else "Rotation"
                            if is_repeat: reason += " (Repeat)"
                            sub_G.add_edge(f"p_{p['p_id']}", f"m_{m['id']}", capacity=1, weight=final_cost, reason=reason)

                    try:
                        sub_flow = nx.min_cost_flow(sub_G)
                        for p in assigned_pnms:
                            p_node = f"p_{p['p_id']}"
                            if p_node in sub_flow:
                                for tgt, flow in sub_flow[p_node].items():
                                    if flow > 0 and tgt != sub_t:
                                        m_id_ex = int(tgt.replace("m_", ""))
                                        m_name = next((m['name'] for m in valid_members if m['id'] == m_id_ex), "Unknown")
                                        edge_d = sub_G.get_edge_data(p_node, tgt)
                                        raw_weight = edge_d.get('weight', 10000)
                                        if raw_weight > 40000: raw_weight -= 50000
                                        calc_cost = raw_weight / 10000.0
                                        rotation_output.append({
                                            'Round': round_num, 'Team ID': t_idx, 'Team Members': team_data['joined_names'],
                                            'PNM ID': p['p_id'], 'PNM Name': p['p_name'], 'Matched Member': m_name,
                                            'Match Cost': round(calc_cost, 4), 'Reason': f"Common: {edge_d.get('reason')}"
                                        })
                                        history.add((p['p_id'], m_id_ex))
                    except nx.NetworkXUnfeasible:
                         fail_reason = f"Unfeasible (RGL {team_rgl_name} removed, insufficient capacity)" if round_num == 1 and team_rgl_name and len(active_members) < len(assigned_pnms) else "Unfeasible"
                         rotation_output.append({'Round': round_num, 'Team ID': t_idx, 'PNM Name': "FLOW FAIL", 'Reason': fail_reason})

                elif method == 'greedy':
                    candidates = []
                    for p in assigned_pnms:
                        for m in active_members:
                            is_repeat = (p['p_id'], m['id']) in history
                            if is_repeat and not must_allow_repeats: continue
                            m_attrs = member_attr_cache.get(m['id'], set())
                            shared = p['p_attrs'].intersection(m_attrs)
                            score = sum(trait_weights.get(t, 1.0) for t in shared)
                            final_score = score - 1000 if is_repeat else score
                            reason = ", ".join(shared) if shared else "Rotation"
                            if is_repeat: reason += " (Repeat)"
                            candidates.append((final_score, p, m, reason, is_repeat))

                    candidates.sort(key=lambda x: x[0], reverse=True)
                    round_pnm_done, round_mem_done = set(), set()

                    for sc, p, m, rs, is_rep in candidates:
                        if p['p_id'] not in round_pnm_done and m['id'] not in round_mem_done:
                            real_score = sc + 1000 if is_rep else sc
                            calc_cost = 1.0 / (1.0 + real_score)
                            rotation_output.append({
                                'Round': round_num, 'Team ID': t_idx, 'Team Members': team_data['joined_names'],
                                'PNM ID': p['p_id'], 'PNM Name': p['p_name'], 'Matched Member': m['name'],
                                'Match Cost': round(calc_cost, 4), 'Reason': f"Common: {rs}" if real_score > 0 else "Greedy Fill"
                            })
                            round_pnm_done.add(p['p_id']); round_mem_done.add(m['id']); history.add((p['p_id'], m['id']))

                    for p in assigned_pnms:
                        if p['p_id'] not in round_pnm_done:
                            for m in active_members:
                                if m['id'] not in round_mem_done:
                                    m_attrs = member_attr_cache.get(m['id'], set())
                                    shared = p['p_attrs'].intersection(m_attrs)
                                    score = sum(trait_weights.get(t, 1.0) for t in shared)
                                    rotation_output.append({
                                        'Round': round_num, 'Team ID': t_idx, 'Team Members': team_data['joined_names'],
                                        'PNM ID': p['p_id'], 'PNM Name': p['p_name'], 'Matched Member': m['name'],
                                        'Match Cost': round(1.0 / (1.0 + score), 4), 'Reason': "Forced Greedy Fill"
                                    })
                                    round_pnm_done.add(p['p_id']); round_mem_done.add(m['id']); history.add((p['p_id'], m['id']))
                                    break
        return rotation_output

    internal_flow_results = run_internal_rotation(assignments_map_flow, method='flow')
    internal_greedy_results = run_internal_rotation(assignments_map_greedy, method='greedy')

    # =========================================================================
    # PHASE C: GENERATE BUMP INSTRUCTIONS
    # =========================================================================
    def generate_bump_instructions(rotation_data):
        if not rotation_data: return []
        df = pd.DataFrame(rotation_data)
        if df.empty or 'Matched Member' not in df.columns: return []
        df = df.sort_values(by=['Team ID', 'PNM ID', 'Round'])
        df['Person_To_Bump'] = df.groupby(['Team ID', 'PNM ID'])['Matched Member'].shift(1)
        instructions = df[df['Person_To_Bump'].notna()].copy()
        instructions['At End Of Round'] = instructions['Round'] - 1
        output = instructions[['Matched Member', 'At End Of Round', 'Person_To_Bump', 'PNM Name']].rename(columns={
            'Matched Member': 'Member (You)', 'Person_To_Bump': 'Go Bump This Person', 'PNM Name': 'Who is with PNM'
        })
        return output.sort_values(by=['Member (You)', 'At End Of Round']).to_dict('records')

    bump_instruct_flow = generate_bump_instructions(internal_flow_results)
    bump_instruct_greedy = generate_bump_instructions(internal_greedy_results)

    # --- 4. Export Results ---
    if global_flow_results:
        df_glob_flow = pd.DataFrame(global_flow_results)
        df_glob_greedy = pd.DataFrame(global_greedy_results)
        df_rot_flow = pd.DataFrame(internal_flow_results)
        df_rot_greedy = pd.DataFrame(internal_greedy_results)
        df_bump_flow = pd.DataFrame(bump_instruct_flow)
        df_bump_greedy = pd.DataFrame(bump_instruct_greedy)

        flow_costs = df_glob_flow['Match Cost'].dropna()
        greedy_costs = df_glob_greedy['Match Cost'].dropna()
        summary_df = pd.DataFrame({
            'Metric': ['Total Matching Cost', 'Average Matching Cost', 'Minimum Matching Cost', 'Maximum Matching Cost', 'Standard Deviation'],
            'Global Network Flow': [round(flow_costs.sum(), 4), round(flow_costs.mean(), 4) if not flow_costs.empty else 0, round(flow_costs.min(), 4) if not flow_costs.empty else 0, round(flow_costs.max(), 4) if not flow_costs.empty else 0, round(flow_costs.std(), 4) if len(flow_costs) > 1 else 0],
            'Global Greedy Algorithm': [round(greedy_costs.sum(), 4), round(greedy_costs.mean(), 4) if not greedy_costs.empty else 0, round(greedy_costs.min(), 4) if not greedy_costs.empty else 0, round(greedy_costs.max(), 4) if not greedy_costs.empty else 0, round(greedy_costs.std(), 4) if len(greedy_costs) > 1 else 0]
        })

        file_name = f"Party_{party}_Match_Analysis.xlsx"

        with pd.ExcelWriter(file_name, engine='xlsxwriter') as writer:
            # Summary and Global sheets (always kept)
            df_glob_flow.to_excel(writer, sheet_name="Global_Matches_Flow", index=False); auto_adjust_columns(writer, "Global_Matches_Flow", df_glob_flow)
            df_glob_greedy.to_excel(writer, sheet_name="Global_Matches_Greedy", index=False); auto_adjust_columns(writer, "Global_Matches_Greedy", df_glob_greedy)
            summary_df.to_excel(writer, sheet_name="Summary_Comparison", index=False); auto_adjust_columns(writer, "Summary_Comparison", summary_df)

            # Rotation Sheets (Dynamic based on bump_order_set)
            if not df_rot_flow.empty:
                sorted_rot_flow = df_rot_flow.sort_values(by=['Team ID', 'Round', 'PNM Name'])
                round_one_flow = sorted_rot_flow[sorted_rot_flow['Round'] == 1].copy()
                if 'Team ID' in sorted_rot_flow.columns: sorted_rot_flow = sorted_rot_flow.drop(columns=['Team ID'])
                if 'Team ID' in round_one_flow.columns: round_one_flow = round_one_flow.drop(columns=['Team ID'])
                if 'Round' in round_one_flow.columns: round_one_flow = round_one_flow.drop(columns=['Round'])

                if bump_order_set == "n":
                    sorted_rot_flow.to_excel(writer, sheet_name="Rotation_Flow", index=False); auto_adjust_columns(writer, "Rotation_Flow", sorted_rot_flow)
                    if not df_bump_flow.empty: df_bump_flow.to_excel(writer, sheet_name="Bump_Logistics_Flow", index=False); auto_adjust_columns(writer, "Bump_Logistics_Flow", df_bump_flow)
                else:
                    round_one_flow.to_excel(writer, sheet_name="Round_1_Matches_Flow", index=False); auto_adjust_columns(writer, "Round_1_Matches_Flow", round_one_flow)

            if not df_rot_greedy.empty:
                sorted_rot_greedy = df_rot_greedy.sort_values(by=['Team ID', 'Round', 'PNM Name'])
                round_one_greedy = sorted_rot_greedy[sorted_rot_greedy['Round'] == 1].copy()
                if 'Team ID' in sorted_rot_greedy.columns: sorted_rot_greedy = sorted_rot_greedy.drop(columns=['Team ID'])
                if 'Team ID' in round_one_greedy.columns: round_one_greedy = round_one_greedy.drop(columns=['Team ID'])
                if 'Round' in round_one_greedy.columns: round_one_greedy = round_one_greedy.drop(columns=['Round'])

                if bump_order_set == "n":
                    sorted_rot_greedy.to_excel(writer, sheet_name="Rotation_Greedy", index=False); auto_adjust_columns(writer, "Rotation_Greedy", sorted_rot_greedy)
                    if not df_bump_greedy.empty: df_bump_greedy.to_excel(writer, sheet_name="Bump_Logistics_Greedy", index=False); auto_adjust_columns(writer, "Bump_Logistics_Greedy", df_bump_greedy)
                else:
                    round_one_greedy.to_excel(writer, sheet_name="Round_1_Matches_Greedy", index=False); auto_adjust_columns(writer, "Round_1_Matches_Greedy", round_one_greedy)

        print(f"Exported {file_name}.\n")
    else:
        print(f"No matches found for Party {party}.\n")